spring.application.name=Web
spring.servlet.multipart.max-file-size=100MB
ocr.azure.key=3xiRFbfh5c7S28B0ioYHi4WkokjiOugIpfLUawRZQkQsidOFgASWJQQJ99BKAC5RqLJXJ3w3AAALACOGm06e
ocr.azure.endpoint=https://contractextractor1.cognitiveservices.azure.com/